#!/usr/bin/env python3
"""Independent checks of generated CSG geometry and an exported STL.

Usage: python verify_folded_belt.py /tmp/belt.csg belt.stl
Dependencies: numpy, shapely, trimesh (see requirements.txt).
The CSG is generated by OpenSCAD, not reconstructed by the solver under test.
"""
import argparse
import ast
import json
import math
import re
from pathlib import Path

import numpy as np
import trimesh
from shapely.geometry import Polygon, LineString
from shapely.ops import unary_union
from shapely.strtree import STRtree


def verify(csg_path, stl_path=None, count=254, gap=2.0, width=9, backing_thickness=1.73,
           max_size=(170,170), min_radius=15, geometry_tolerance=.02):
    text = Path(csg_path).read_text()
    matrices = [np.array(ast.literal_eval(x), dtype=float) for x in re.findall(r'multmatrix\((\[.*?\])\)', text)]
    polygons = [np.array(ast.literal_eval(x), dtype=float) for x in re.findall(r'polygon\(points = (\[.*?\]), paths', text)]
    assert len(polygons) == count + 2, (len(polygons), count)
    prefix = len(matrices) - 2 * count
    assert prefix in (1,2), len(matrices)
    global_transform = np.eye(4)
    for matrix in matrices[:prefix]: global_transform = global_transform @ matrix
    def transformed(points, matrix=global_transform):
        return (np.c_[points,np.zeros(len(points)),np.ones(len(points))] @ matrix.T)[:,:2]
    polygons[:2] = [transformed(p) for p in polygons[:2]]
    outer, inner = map(Polygon, polygons[:2])
    assert outer.is_valid and inner.is_valid and outer.contains(inner)
    backing = outer.difference(inner)
    teeth = []
    for i, polygon in enumerate(polygons[2:]):
        # First matrix translates the complete belt; the next two locate each tooth.
        transform = global_transform @ matrices[prefix + i * 2] @ matrices[prefix + 1 + i * 2]
        vertices = np.c_[polygon, np.zeros(len(polygon)), np.ones(len(polygon))] @ transform.T
        tooth = Polygon(vertices[:, :2])
        assert tooth.is_valid
        assert tooth.intersection(backing).area > 0.01, f'detached tooth {i}'
        assert np.allclose(polygon, polygons[2], atol=0, rtol=0), 'tooth profile changed'
        teeth.append(tooth)
    combined = unary_union([backing, *teeth])
    assert combined.geom_type == 'Polygon' and combined.is_valid
    assert len(combined.interiors) == 1, 'unintended bridge or missing closure'
    # All non-neighbor teeth must remain clear, independently of the SCAD tube test.
    clearance = min(teeth[i].distance(teeth[j]) for i in range(count) for j in range(i+1, count)
                    if min(j-i, count-(j-i)) > 1)
    assert clearance > 0, clearance # Local neighboring teeth need not have the nonlocal track gap.
    bounds = np.array(combined.bounds)
    footprint = bounds[2:] - bounds[:2]
    assert np.all(footprint <= np.array(max_size)+.001), footprint
    # Independently recheck the conservative swept disk against the emitted
    # reference polyline. Reserve 0.001 mm for CSG text rounding per boundary.
    reference = polygons[1]
    edges = [LineString([p, reference[(i+1)%len(reference)]]) for i,p in enumerate(reference)]
    lengths = np.array([edge.length for edge in edges])
    stations = np.r_[0,np.cumsum(lengths)]
    envelope = max(np.linalg.norm(polygons[2],axis=1).max(),backing_thickness)
    error = min(geometry_tolerance/2,.01,-polygons[2][:,1].min()/10)
    distance_limit = 2*(envelope+error+.001)+gap
    tree = STRtree(edges)
    distances = []
    for i, edge in enumerate(edges):
        for j in tree.query(edge, predicate='dwithin', distance=distance_limit+.5):
            if j <= i: continue
            mid = (stations[j]+stations[j+1]-stations[i]-stations[i+1])/2
            apart = min(mid,stations[-1]-mid)+(lengths[i]+lengths[j])/2
            if apart >= math.pi*min_radius:
                distances.append(edge.distance(edges[j]))
    envelope_clearance = min(distances)-2*(envelope+error+.001) if distances else gap
    assert envelope_clearance >= gap, envelope_clearance
    result = {'tooth_count': count, 'tooth_attachment': 'all positive overlap',
              'planar_topology': 'one connected polygon, one hole',
              'footprint_mm': footprint.tolist(), 'nonneighbor_tooth_clearance_mm': clearance,
              'independent_envelope_clearance_lower_bound_mm': envelope_clearance}
    if stl_path:
        mesh = trimesh.load_mesh(stl_path, process=True)
        assert isinstance(mesh, trimesh.Trimesh)
        assert mesh.is_watertight and mesh.is_winding_consistent
        assert len(mesh.split(only_watertight=False)) == 1
        assert mesh.euler_number == 0, f'expected genus one, Euler={mesh.euler_number}'
        assert mesh.volume > 0 and np.all(mesh.extents[:2] <= np.array(max_size)+.001)
        assert abs(mesh.extents[2] - width) < 0.001
        # Extruded cross-section volume independently matches the 2D construction.
        assert abs(mesh.volume - combined.area * width) / mesh.volume < 0.0001
        result.update({'mesh': 'watertight, consistently oriented, one component, genus one',
                       'mesh_footprint_mm': mesh.extents.tolist(), 'mesh_volume_mm3': float(mesh.volume)})
    result['physical_pulley_fit'] = 'not tested'
    return result


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('csg', type=Path)
    parser.add_argument('stl', type=Path, nargs='?')
    parser.add_argument('--count', type=int, default=254)
    parser.add_argument('--width',type=float,default=9)
    parser.add_argument('--backing',type=float,default=1.73)
    parser.add_argument('--radius',type=float,default=15)
    parser.add_argument('--gap',type=float,default=2)
    parser.add_argument('--size',type=float,nargs=2,default=[170,170])
    parser.add_argument('--geometry-tolerance',type=float,default=.02)
    args = parser.parse_args()
    print(json.dumps(verify(args.csg,args.stl,args.count,args.gap,args.width,args.backing,args.size,args.radius,args.geometry_tolerance), indent=2))
